### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by Ssionn**
Nothing to see here

### CODE REVIEW

**Comment by TreyBastian** [comment]
I think we need to look at some of the formatting in this PR. Make sure you are using configured formatters to keep the code quality high.

**Comment by Ssionn** [comment]
> I think we need to look at some of the formatting in this PR. Make sure you are using configured formatters to keep the code quality high.

Everything 0 spaces

**Comment by TreyBastian** [comment]
aww man looks like we have conflicts now can't merge until those are resolved

**Comment by Ssionn** [comment]
Well I guess we can't fix it, neovim is not a web editor
CleanShot 2024-08-29 at 19 54 02

**Pull request closed without merging**
